# Generated by Django 4.0.4 on 2022-06-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Std_data',
            fields=[
                ('std_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=90)),
            ],
        ),
    ]
