# Generated by Django 4.0.4 on 2022-06-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='std_data',
            name='address',
            field=models.CharField(default='Nothing here', max_length=16),
        ),
    ]
