# Generated by Django 4.0.4 on 2022-06-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('i_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
            ],
        ),
    ]
