# Generated by Django 4.0.4 on 2022-06-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='comment',
            field=models.CharField(default='nothing here ', max_length=40),
        ),
    ]
